scalar DateTime

type Aeropuerto {
  id: ID!
  localizacion: String!
  rutas: [Ruta!]!
  aviones: [Avion!]!
}

type Ruta{
  id: ID!
  fechaHoraSalida: DateTime!
  kilometros: Int!
}

type Avion{
  id: ID!
  matricula: String!
  velocidadHora: Int!
  pasajeros: [Pasajero!]!
}

type Pasajero {
  id: ID!
  nombre: String!
  apellido: String!
}

# Reserved type in GraphQL for querying
# Root type for all query operations
type Query {
  #NameOfTheFunction: TypeToReturn
  listarAeropuertos: [Aeropuerto!]!
  #NameOfTheFunction(ArgumentsToSendInTheQuery): TypeToReturn
  obtenerAeropuertoPorId(
    # Since it's a query by id --> id must be mandatory
    id: ID!
    ): Aeropuerto
  obtenerAeropuerto(id: ID, localizacion: String): Aeropuerto
}
